"""
EnGenie Chat API

Endpoint for EnGenie Chat queries. Routes all queries through the
orchestrator (web search → LLM grounded response).
"""

import re
import logging
from flask import Blueprint, request, jsonify, session

from .engenie_chat_orchestrator import run_engenie_chat_query
from .engenie_chat_memory import (
    get_session_summary, clear_session, cleanup_expired_sessions
)

# Import consolidated decorators
from common.utils.auth_decorators import login_required

logger = logging.getLogger(__name__)


def _sanitize_markdown(text: str) -> str:
    """
    Clean up common LLM markdown formatting issues before sending to the frontend.

    Problems addressed:
    1. Literal <br>, <br/>, <br /> tags inside markdown table cells — these are
       generated by some LLMs despite instructions not to use them, and they break
       remarkGfm table rendering in React, causing garbled line breaks.
       Fix: replace with a comma+space so the cell content stays readable.
    2. Escaped newlines (\\n literal two-char sequence) that appear as raw text.
       Fix: replace with a real newline.
    """
    if not text:
        return text

    # 1. Replace <br> variants with ", " so table cells stay on one line
    text = re.sub(r'<br\s*/?>', ', ', text, flags=re.IGNORECASE)

    # 2. Replace literal \\n (escaped newline written by LLM) with real newline
    text = text.replace('\\n', '\n')

    return text

# Create blueprint
engenie_chat_bp = Blueprint('engenie_chat', __name__, url_prefix='/api/engenie-chat')


@engenie_chat_bp.route('/query', methods=['POST'])
@login_required
def query_endpoint():
    """
    Main query endpoint for EnGenie Chat.

    Request:
        {
            "query": "What is Rosemount 3051S?",
            "session_id": "optional_session_id"
        }

    Response:
        {
            "success": true,
            "answer": "The Rosemount 3051S is...",
            "source": "llm",
            "found_in_database": false,
            "sources_used": ["llm", "web_search"],
            "results_count": 2,
            "is_follow_up": false,
            "note": ""
        }
    """
    try:
        data = request.get_json()
        if not data:
            return jsonify({
                'success': False,
                'error': 'Request body required',
                'answer': 'Please provide a query.'
            }), 400
        
        query = data.get('query', '').strip()
        if not query:
            return jsonify({
                'success': False,
                'error': 'Query is required',
                'answer': 'Please enter your question.'
            }), 400

        # Get or generate session ID
        session_id = data.get('session_id') or session.get('engenie_chat_session_id')
        if not session_id:
            session_id = f"ec_{session.get('user_id', 'anon')}_{id(request)}"
            session['engenie_chat_session_id'] = session_id

        logger.info(f"[ENGENIE_CHAT_API] Query from session {session_id}: {query[:100]}...")

        # Run the orchestrated query
        result = run_engenie_chat_query(
            query=query,
            session_id=session_id
        )
        
        # Format response for frontend
        response = {
            'success': result.get('success', False),
            'answer': _sanitize_markdown(result.get('answer', '')),
            'source': result.get('source', 'unknown'),
            'found_in_database': result.get('found_in_database', False),
            'awaiting_confirmation': False,
            'sources_used': result.get('sources_used', []),
            'results_count': len(result.get('sources_used', [])),
            'is_follow_up': result.get('is_follow_up', False),
            'classification': result.get('classification', {}),
            'note': ''
        }

        # Add note if multiple sources used
        if len(response['sources_used']) > 1:
            response['note'] = f"Combined information from: {', '.join(response['sources_used'])}"

        return jsonify(response)
        
    except Exception as e:
        logger.error(f"[ENGENIE_CHAT_API] Error: {e}", exc_info=True)
        return jsonify({
            'success': False,
            'error': str(e),
            'answer': 'Sorry, something went wrong. Please try again.',
            'source': 'unknown',
            'found_in_database': False,
            'awaiting_confirmation': False,
            'sources_used': []
        }), 500


@engenie_chat_bp.route('/session', methods=['GET'])
@login_required
def get_session_info():
    """Get current session summary."""
    try:
        session_id = session.get('engenie_chat_session_id')
        if not session_id:
            return jsonify({
                'success': True,
                'session': None,
                'message': 'No active session'
            })
        
        summary = get_session_summary(session_id)
        return jsonify({
            'success': True,
            'session': summary
        })
        
    except Exception as e:
        logger.error(f"[ENGENIE_CHAT_API] Session info error: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@engenie_chat_bp.route('/session', methods=['DELETE'])
@login_required
def clear_session_endpoint():
    """Clear current session."""
    try:
        session_id = session.get('engenie_chat_session_id')
        if session_id:
            clear_session(session_id)
            session.pop('engenie_chat_session_id', None)
        
        return jsonify({
            'success': True,
            'message': 'Session cleared'
        })
        
    except Exception as e:
        logger.error(f"[ENGENIE_CHAT_API] Clear session error: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@engenie_chat_bp.route('/cleanup', methods=['POST'])
@login_required
def cleanup_sessions():
    """Cleanup expired sessions (admin only)."""
    try:
        removed = cleanup_expired_sessions()
        return jsonify({
            'success': True,
            'removed_count': removed,
            'message': f'Cleaned up {removed} expired sessions'
        })
        
    except Exception as e:
        logger.error(f"[ENGENIE_CHAT_API] Cleanup error: {e}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


@engenie_chat_bp.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint."""
    return jsonify({
        'status': 'healthy',
        'service': 'engenie_chat'
    })
